name: Deploy Dockerized React App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: docker-react            # Name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'             # Path to your app root (Dockerfile location)
  DOCKER_IMAGE_NAME: cygnetops/react-test    # Your Docker Hub or ACR image name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }} -f Dockerfile.dev .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.DOCKER_IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Docker container to Azure Web App
        uses: azure/webapps-container-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          images: ${{ env.DOCKER_IMAGE_NAME }}
